# Generated by Django 4.1.1 on 2022-10-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BLOGGEUR', 'Créateur'), ('INTERNAUTE', 'Abonné')], max_length=10, verbose_name='Rôle'),
        ),
    ]
