# Generated by Django 4.1.2 on 2022-11-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Photo de profil'),
        ),
    ]
