# Generated by Django 4.1.1 on 2022-10-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enregistrements',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Save'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Like'),
            preserve_default=False,
        ),
    ]
