# Generated by Django 4.1.1 on 2022-11-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_photo_articles_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date'], 'verbose_name': 'Commentaire'},
        ),
    ]
