# Generated by Django 4.1.1 on 2022-11-06 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0005_articles_likes_delete_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='enregistrements',
            field=models.ManyToManyField(related_name='article_save', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Enregistrements',
        ),
    ]
