# Generated by Django 4.1.1 on 2022-11-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_articles_enregistrements_delete_enregistrements'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
